name: Build
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-24.04
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
        shell: bash
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: "Run script"
        run: |
          export OS="linux"
          source ./ci/setup-env.sh
          source ./ci/test.sh
          source ./ci/build.sh
        shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: bin
          retention-days: 7
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
        shell: bash
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: "Run script"
        run: |
          export OS="mac"
          source ./ci/setup-env.sh
          source ./ci/test.sh
          source ./ci/build.sh
        shell: bash

      - name: Setup temporary keychain and add application signing certificate
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_APPLICATION }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_APPLICATION_PASSWORD }}

      - name: Codesign AU plugin
        working-directory: ${{ github.workspace }}/ci/bin
        run: codesign --force -s "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" osci-render.component --timestamp

      - name: Codesign VST3 plugin
        working-directory: ${{ github.workspace }}/ci/bin
        run: codesign --force -s "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" osci-render.vst3 --timestamp

      - name: Codesign Standalone app
        working-directory: ${{ github.workspace }}/ci/bin
        run: codesign --force -s "${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}" osci-render.app --timestamp

      - name: Download Packages installer build tool
        run: wget http://s.sudre.free.fr/files/Packages_1211_dev.dmg

      - name: Mount Packages image
        run: hdiutil attach Packages.dmg

      - name: Install Packages
        run: sudo installer -pkg /Volumes/Packages\ 1.2.11/Install\ Packages.pkg -target /

      - name: Build installer
        run: packagesbuild --project "${{ github.workspace }}/packaging/osci-render.pkgproj"

      - name: Setup temporary keychain and add installer signing certificate
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_INSTALLER }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_INSTALLER_PASSWORD }}

      - name: Sign installer
        run: productsign -s "${{ secrets.APPLE_DEVELOPER_ID_INSTALLER }}" "${{ github.workspace }}/packaging/osci-render.pkg" "${{ github.workspace }}/bin/osci-render.pkg"
    
      - name: Notarize installer
        run: npx notarize-cli --file "${{ github.workspace }}/packaging/osci-render-signed.pkg" --bundle-id com.osci-render.pkg --username ${{ secrets.APPLE_ID }} --password ${{ secrets.APPLE_NOTARIZATION_PW }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: bin
          retention-days: 7
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
        shell: bash
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
      - name: NuGet Sources
        run: nuget sources
      - name: "Run script"
        run: |
          export OS="win"
          source ./ci/setup-env.sh
          source ./ci/test.sh
          source ./ci/build.sh
        shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binaries
          path: bin
          retention-days: 7
